version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      REDISCLOUD_URL: redis://redis:6379/0
      PORT: 8081

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"